version: '3.7'

services:

  # ----- CI / Tools -----
  go:
    image: ${container_repo}/arcadium/go:latest
    working_dir: /go/src/arcadium.dev/core
    entrypoint:
      - go
    volumes:
      - .:/go/src/arcadium.dev/core
      - go_cache:/root/.cache/go-build


volumes:
  go_cache:
