name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '**'

jobs:

  build:
    strategy:
      matrix:
        go-version: [ 1.17.x, 1.18.x ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        stable: false
        go-version: ${{ matrix.go-version }}

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        make test
