name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        make test
