name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install tools
      run: make install

    - name: Lint
      run: |
        export PATH="${PWD}/bin:${PATH}"
        make lint

    - name: Test
      run: |
        export PATH="${PWD}/bin:${PATH}"
        make test
