name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        go: [ '1.21', '1.22' ]

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        check-latest: true

    - name: lint
      run: |
        make lint

    - name: test
      run: |
        make test
